export const CREATE_SESSION = "CREATE_SESSION";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_FAIL = "CREATE_SESSION_FAIL";
export const RESET_FARES = "RESET_FARES";
export const SET_SOURCE_AND_DESTINATION = "SET_SOURCE_AND_DESTINATION";